version: '3'

services:
  app:
    image: kerwin1202/chatgpt-web # 总是使用latest,更新时重新pull该tag镜像即可
    container_name: chatgptweb
    restart: unless-stopped
    ports:
      - 3002:3002
    depends_on:
      - database
    environment:
      TZ: Asia/Shanghai
    env_file:
      - ../service/.env
    links:
      - database

  database:
    image: mongo
    ports:
      - '27017:27017'
    expose:
      - '27017'
    volumes:
      - mongodb:/data/db
    environment:
      TZ: Asia/Shanghai
      MONGO_INITDB_ROOT_USERNAME: chatgpt
      MONGO_INITDB_ROOT_PASSWORD: xxxx
      MONGO_INITDB_DATABASE: chatgpt

  mongo-gui:
    container_name: mongo-gui
    image: ugleiton/mongo-gui
    restart: always
    ports:
      - '4321:4321'
    environment:
      - TZ=Asia/Shanghai
      - MONGO_URL=mongodb://chatgpt:xxxx@database:27017
    links:
      - database
    depends_on:
      - database

  nginx:
    image: nginx:alpine
    restart: unless-stopped
    ports:
      - '80:80'
    expose:
      - '80'
    environment:
      - TZ=Asia/Shanghai
    volumes:
      - ./nginx/html:/usr/share/nginx/html
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    links:
      - app

volumes:
  mongodb: {}
